### ISSUE TITLE
Empty rcore.json in German translation

### ISSUE THREAD

**Issue by ombre5733** [Kamalisk/arkhamdb-json-data#1129]
There is an empty rcore.json file in the folder 'translations/de/pack/core'. This file is not present for other languages. I'm not sure, it should be there.

**Comment by elkeinkrad** [comment]
Empty rcore.json in translation file is fine. Another case will be empty file, like korean version of this. [[link]](https://github.com/Kamalisk/arkhamdb-json-data/blob/master/translations/ko/pack/core/rcore.json)

This is because all items in original rcore.json have no traits for translation (such as name, text, traits...), so that the script omits all items when converting. Thus, the file will be empty. If you want to change the card in revised core, you need to change the original version of card. i.e. Old Book of the Lore in where the god dwells pack.

Additionally, as I know, the maintainer run script which fills non-existance file from english version in server, so that all translation folders may have empty rcore.json file in server.

**Comment by ombre5733** [comment]
Thanks for the explanation. Closing this issue then.
