### ISSUE TITLE
Help understanding back_link, double_sided and hidden attributes

### ISSUE THREAD

**Issue by tarogers** [Kamalisk/arkhamdb-json-data#539]
Hello, I'm attempting to understand the intended usage of back_link, double_sided and hidden attributes.

Mythos card code 03325b for instance, has a back_link to 03325 but is not double_sided and is also hidden.  The front side, code 03325 is also not double_sided but does not contain a back_link to 03325b

Conversely, code 05264 contains *both* double_sided and back_link to 05264b. And code 05264b has neither double_sided nor back_link but does contain hidden.

Many cards contain double_sided but no back_link, so I speculate that for these cases we just assume to append 'b' for the back code.

For hidden, it seems to appear mostly on back_sides ... but not always - for example: code 03221 (The Organist)

I'd appreciate any clarification.  I'm happy to help make changes if some of this data is in error.

**Comment by drawntotheflame** [comment]
Hi @tarogers, let me get back to you on this - part of it was around how it displayed on the db to the public, but there may be some consistencies that need ironing out. 
In brief, now: double-sided cards that switch card type, such as agenda 1 in Midnight Masks, split into two single-sided cards for the purposes of data here, rather than being a double-sided agenda+enemy or what have you - so that's why some cards have back_links rather than simply being double sided. But I'll look at the numbers you mention.

**Comment by fspoettel** [comment]
@zzorba this can be closed: addressed and these consistency issues have now been fixed. new issues should be tracked separately.
